### ISSUE TITLE
Doesn't work, gives an error

### ISSUE THREAD

**Issue by Comitant** [NothingNaN/YoutubeCommunityScraper#1]
I get this whenever running the code:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\*\AppData\Local\Programs\Python\Python311\Scripts\yp-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\*\AppData\Local\Programs\Python\Python311\Lib\site-packages\yp_dl\yp_dl.py", line 269, in run
    cookies = {"SOCS": get_SOCS_cookie()}
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\*\AppData\Local\Programs\Python\Python311\Lib\site-packages\yp_dl\yp_dl.py", line 24, in get_SOCS_cookie
    form = result.html.xpath('/html/body/c-wiz/div/div/div/div[2]/div[1]/div[3]/div[1]/form[1]')[0].html
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by NothingNaN** [comment]
Thanks for bringing this to my attention. It looks like the function that retrieves the SOCS cookie that enables you to navigate youtube, and by extension allows this project to scrape it, fails. Specifically, it fails at retrieving the html form that handles the consent when it comes to accepting cookies and terms of conditions (standard stuff that YouTube redirects you to when first landing on their page). This means YouTube might have changed the format of the consent page (https://consent.youtube.com/). However, the script still works for me as expected. Is it possible you have been served YouTube's new experimental UI changes by chance (probably based on IP)? If so, can you please go in incognito mode and access this page "https://www.youtube.com/feed" (you will be redirected to youtube's consent page), save it with Ctrl+S, zip the folder and the html file generated together and attach it here as a comment?

**Comment by Comitant** [comment]
Yeah it seems my IP is given a different UI, I just tried it with a VPN and it worked. I think the problem is that my own IP never gets a consent page from YouTube, even in incognito.

[YouTube.zip](https://github.com/user-attachments/files/16117177/YouTube.zip)

**Comment by NothingNaN** [comment]
Interesting. Since no consent page is served to you, I'll add a default SOCS cookie to cover cases like yours, although it has an expiration date of 2 years from the moment it's generated. I'll also make the get_SOCS_cookie function get the cookie once and store it in a file so that it doesn't have ask for it from youtube every time. However, this is all pointless if the UI changes break the script further down (unclear right now). 

As for the zip folder you've attached, it seems you forgot to add the folder with the css (a folder and the html page with the same name are downloaded to your PC after you save the page - at least when done from Chrome, not sure about other browsers). So I can't know how different it looks because the page is incomplete. But does it look something like [this](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fnew-youtube-ui-or-just-me-v0-43m6eygk56kc1.png%3Fwidth%3D1080%26crop%3Dsmart%26auto%3Dwebp%26s%3D3e96d0679eac199f24ba6ddf13771b04cc2b6c89) by chance?

**Comment by Comitant** [comment]
Awesome, thank you!

> As for the zip folder you've attached, it seems you forgot to add the folder with the css

Oh I was saving as HTML only and not complete web page. This should be the full thing:
[YouTube.zip](https://github.com/user-attachments/files/16117393/YouTube.zip)

**Comment by NothingNaN** [comment]
The UI looks the same. I can't tell a difference on the homepage, even though it's incomplete offline.

I must mention I was slightly wrong about the redirection. I forgot that when going straight to "https://www.youtube.com/" it gives you the form as a popup (my fault there), but if you try to access "https://www.youtube.com/feed" you should get redirected to a consent page. 

If indeed no form is presented to you and no redirection happens, then it's safe to assume it's considered as accepted by default and I can just return the cookie on first access. This is what I've done as of commit 5c339b7. If that fails too, you'll be using the predefined SOCS cookie within the project. The SOCS cookie will now be stored in a file within the project directory called `cookies.txt` to cut down on the time it takes to retrieve it from YouTube every time.

Please tell me if all works well so I can close the issue.

**Comment by Comitant** [comment]
Both links give no popup or redirect oddly enough. Like you said, I think it is accepted as default for my IP.

The update does indeed function properly. Thanks a lot for the help!
